package main

// Valid blocks.
var (
	BlockAir          = initSimple("air", simpleConfig{NotCullAgainst: true})
	BlockStone        = initSimple("stone", simpleConfig{})
	BlockGrass        = initGrass()
	BlockDirt         = initSimple("dirt", simpleConfig{})
	BlockCobblestone  = initSimple("cobblestone", simpleConfig{})
	BlockPlanks       = initSimple("planks", simpleConfig{})
	BlockSapling      = initSimple("sapling", simpleConfig{NotCullAgainst: true})
	BlockBedrock      = initSimple("bedrock", simpleConfig{})
	BlockFlowingWater = initLiquid("flowing_water", false)
	BlockWater        = initLiquid("water", false)
	BlockFlowingLava  = initLiquid("flowing_lava", true)
	BlockLava         = initLiquid("lava", true)
	BlockSand         = initSimple("sand", simpleConfig{})
	BlockGravel       = initSimple("gravel", simpleConfig{})
	BlockGoldOre      = initSimple("gold_ore", simpleConfig{})
	BlockIronOre      = initSimple("iron_ore", simpleConfig{})
	BlockCoalOre      = initSimple("coal_ore", simpleConfig{})
	BlockLog          = initLog("log")
	BlockLeaves       = initLeaves("leaves")
	BlockSponge       = initSimple("sponge", simpleConfig{})
)
