// GENERATED BY PROTOCOL_BUILDER
// DO NOT TOUCH

package protocol

import (
	"bytes"
	"io"
)

func (h *Handshake) id() int { return 0 }
func (h *Handshake) write(w *bytes.Buffer) error {
	var err error
	var tmp [2]byte
	if err = writeVarInt(w, h.ProtocolVersion); err != nil {
		return err
	}
	if err = writeString(w, h.Host); err != nil {
		return err
	}
	tmp[0] = byte(h.Port >> 8)
	tmp[1] = byte(h.Port >> 0)
	if _, err = w.Write(tmp[:2]); err != nil {
		return err
	}
	if err = writeVarInt(w, h.Next); err != nil {
		return err
	}
	return nil
}
func (h *Handshake) read(r *bytes.Reader) error {
	var err error
	var tmp [2]byte
	if h.ProtocolVersion, err = readVarInt(r); err != nil {
		return err
	}
	if h.Host, err = readString(r); err != nil {
		return err
	}
	if _, err = io.ReadFull(r, tmp[:2]); err != nil {
		return err
	}
	h.Port = (uint16(tmp[1]) << 0) | (uint16(tmp[0]) << 8)
	if h.Next, err = readVarInt(r); err != nil {
		return err
	}
	return nil
}

func init() {
	packetCreator[Handshaking][serverbound][0] = func() Packet { return &Handshake{} }
}
