// Generated by protocol_builder
// Do not edit

package protocol

import (
	"fmt"
	"io"
	"math"
)

func (l *LoginStart) id() int { return 0 }
func (l *LoginStart) write(ww io.Writer) (err error) {
	if err = WriteString(ww, l.Username); err != nil {
		return
	}
	return
}
func (l *LoginStart) read(rr io.Reader) (err error) {
	if l.Username, err = ReadString(rr); err != nil {
		return
	}
	return
}

func (e *EncryptionResponse) id() int { return 1 }
func (e *EncryptionResponse) write(ww io.Writer) (err error) {
	if err = WriteVarInt(ww, VarInt(len(e.SharedSecret))); err != nil {
		return
	}
	if _, err = ww.Write(e.SharedSecret); err != nil {
		return
	}
	if err = WriteVarInt(ww, VarInt(len(e.VerifyToken))); err != nil {
		return
	}
	if _, err = ww.Write(e.VerifyToken); err != nil {
		return
	}
	return
}
func (e *EncryptionResponse) read(rr io.Reader) (err error) {
	var tmp0 VarInt
	if tmp0, err = ReadVarInt(rr); err != nil {
		return
	}
	if tmp0 > math.MaxInt16 {
		return fmt.Errorf("array larger than max value: %d > %d", tmp0, math.MaxInt16)
	}
	if tmp0 < 0 {
		return fmt.Errorf("negative array size: %d < 0", tmp0)
	}
	e.SharedSecret = make([]byte, tmp0)
	if _, err = rr.Read(e.SharedSecret); err != nil {
		return
	}
	var tmp1 VarInt
	if tmp1, err = ReadVarInt(rr); err != nil {
		return
	}
	if tmp1 > math.MaxInt16 {
		return fmt.Errorf("array larger than max value: %d > %d", tmp1, math.MaxInt16)
	}
	if tmp1 < 0 {
		return fmt.Errorf("negative array size: %d < 0", tmp1)
	}
	e.VerifyToken = make([]byte, tmp1)
	if _, err = rr.Read(e.VerifyToken); err != nil {
		return
	}
	return
}

func init() {
	packetCreator[Login][serverbound][0] = func() Packet { return &LoginStart{} }
	packetCreator[Login][serverbound][1] = func() Packet { return &EncryptionResponse{} }
}
