// Generated by protocol_builder
// Do not edit

package protocol

import (
	"encoding/json"
	"fmt"
	"io"
	"math"
)

func (l *LoginDisconnect) id() int { return 0 }
func (l *LoginDisconnect) write(ww io.Writer) (err error) {
	var tmp0 []byte
	if tmp0, err = json.Marshal(&l.Reason); err != nil {
		return
	}
	tmp1 := string(tmp0)
	if err = WriteString(ww, tmp1); err != nil {
		return
	}
	return
}
func (l *LoginDisconnect) read(rr io.Reader) (err error) {
	var tmp0 string
	if tmp0, err = ReadString(rr); err != nil {
		return err
	}
	if err = json.Unmarshal([]byte(tmp0), &l.Reason); err != nil {
		return
	}
	return
}

func (e *EncryptionRequest) id() int { return 1 }
func (e *EncryptionRequest) write(ww io.Writer) (err error) {
	if err = WriteString(ww, e.ServerID); err != nil {
		return
	}
	if err = WriteVarInt(ww, VarInt(len(e.PublicKey))); err != nil {
		return
	}
	if _, err = ww.Write(e.PublicKey); err != nil {
		return
	}
	if err = WriteVarInt(ww, VarInt(len(e.VerifyToken))); err != nil {
		return
	}
	if _, err = ww.Write(e.VerifyToken); err != nil {
		return
	}
	return
}
func (e *EncryptionRequest) read(rr io.Reader) (err error) {
	if e.ServerID, err = ReadString(rr); err != nil {
		return
	}
	var tmp0 VarInt
	if tmp0, err = ReadVarInt(rr); err != nil {
		return
	}
	if tmp0 > math.MaxInt16 {
		return fmt.Errorf("array larger than max value: %d > %d", tmp0, math.MaxInt16)
	}
	if tmp0 < 0 {
		return fmt.Errorf("negative array size: %d < 0", tmp0)
	}
	e.PublicKey = make([]byte, tmp0)
	if _, err = rr.Read(e.PublicKey); err != nil {
		return
	}
	var tmp1 VarInt
	if tmp1, err = ReadVarInt(rr); err != nil {
		return
	}
	if tmp1 > math.MaxInt16 {
		return fmt.Errorf("array larger than max value: %d > %d", tmp1, math.MaxInt16)
	}
	if tmp1 < 0 {
		return fmt.Errorf("negative array size: %d < 0", tmp1)
	}
	e.VerifyToken = make([]byte, tmp1)
	if _, err = rr.Read(e.VerifyToken); err != nil {
		return
	}
	return
}

func (l *LoginSuccess) id() int { return 2 }
func (l *LoginSuccess) write(ww io.Writer) (err error) {
	if err = WriteString(ww, l.UUID); err != nil {
		return
	}
	if err = WriteString(ww, l.Username); err != nil {
		return
	}
	return
}
func (l *LoginSuccess) read(rr io.Reader) (err error) {
	if l.UUID, err = ReadString(rr); err != nil {
		return
	}
	if l.Username, err = ReadString(rr); err != nil {
		return
	}
	return
}

func (s *SetInitialCompression) id() int { return 3 }
func (s *SetInitialCompression) write(ww io.Writer) (err error) {
	if err = WriteVarInt(ww, s.Threshold); err != nil {
		return
	}
	return
}
func (s *SetInitialCompression) read(rr io.Reader) (err error) {
	if s.Threshold, err = ReadVarInt(rr); err != nil {
		return
	}
	return
}

func init() {
	packetCreator[Login][clientbound][0] = func() Packet { return &LoginDisconnect{} }
	packetCreator[Login][clientbound][1] = func() Packet { return &EncryptionRequest{} }
	packetCreator[Login][clientbound][2] = func() Packet { return &LoginSuccess{} }
	packetCreator[Login][clientbound][3] = func() Packet { return &SetInitialCompression{} }
}
