// Generated by protocol_builder
// Do not edit

package protocol

import (
	"encoding/json"
	"io"
)

func (s *StatusResponse) id() int { return 0 }
func (s *StatusResponse) write(ww io.Writer) (err error) {
	var tmp0 []byte
	if tmp0, err = json.Marshal(&s.Status); err != nil {
		return
	}
	tmp1 := string(tmp0)
	if err = WriteString(ww, tmp1); err != nil {
		return
	}
	return
}
func (s *StatusResponse) read(rr io.Reader) (err error) {
	var tmp0 string
	if tmp0, err = ReadString(rr); err != nil {
		return err
	}
	if err = json.Unmarshal([]byte(tmp0), &s.Status); err != nil {
		return
	}
	return
}

func (s *StatusPong) id() int { return 1 }
func (s *StatusPong) write(ww io.Writer) (err error) {
	var tmp [8]byte
	tmp[0] = byte(s.Time >> 56)
	tmp[1] = byte(s.Time >> 48)
	tmp[2] = byte(s.Time >> 40)
	tmp[3] = byte(s.Time >> 32)
	tmp[4] = byte(s.Time >> 24)
	tmp[5] = byte(s.Time >> 16)
	tmp[6] = byte(s.Time >> 8)
	tmp[7] = byte(s.Time >> 0)
	if _, err = ww.Write(tmp[:8]); err != nil {
		return
	}
	return
}
func (s *StatusPong) read(rr io.Reader) (err error) {
	var tmp [8]byte
	if _, err = rr.Read(tmp[:8]); err != nil {
		return
	}
	s.Time = int64((uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56))
	return
}

func init() {
	packetCreator[Status][clientbound][0] = func() Packet { return &StatusResponse{} }
	packetCreator[Status][clientbound][1] = func() Packet { return &StatusPong{} }
}
