// GENERATED BY PROTOCOL_BUILDER
// DO NOT TOUCH

package protocol

import (
	"bytes"
	"io"
)

func (s *StatusResponse) id() int { return 0 }
func (s *StatusResponse) write(w *bytes.Buffer) error {
	var err error
	if err = writeString(w, s.Status); err != nil {
		return err
	}
	return nil
}
func (s *StatusResponse) read(r *bytes.Reader) error {
	var err error
	if s.Status, err = readString(r); err != nil {
		return err
	}
	return nil
}

func (s *StatusPong) id() int { return 1 }
func (s *StatusPong) write(w *bytes.Buffer) error {
	var err error
	var tmp [8]byte
	tmp[0] = byte(s.Time >> 56)
	tmp[1] = byte(s.Time >> 48)
	tmp[2] = byte(s.Time >> 40)
	tmp[3] = byte(s.Time >> 32)
	tmp[4] = byte(s.Time >> 24)
	tmp[5] = byte(s.Time >> 16)
	tmp[6] = byte(s.Time >> 8)
	tmp[7] = byte(s.Time >> 0)
	if _, err = w.Write(tmp[:8]); err != nil {
		return err
	}
	return nil
}
func (s *StatusPong) read(r *bytes.Reader) error {
	var err error
	var tmp [8]byte
	if _, err = io.ReadFull(r, tmp[:8]); err != nil {
		return err
	}
	s.Time = int64((uint64(tmp[7]) << 0) | (uint64(tmp[6]) << 8) | (uint64(tmp[5]) << 16) | (uint64(tmp[4]) << 24) | (uint64(tmp[3]) << 32) | (uint64(tmp[2]) << 40) | (uint64(tmp[1]) << 48) | (uint64(tmp[0]) << 56))
	return nil
}

func init() {
	packetCreator[Status][clientbound][0] = func() Packet { return &StatusResponse{} }
	packetCreator[Status][clientbound][1] = func() Packet { return &StatusPong{} }
}
